#!/bin/sh

for i in "$@"; do
    case $i in
        -n) shift; namespace="$1"; shift;;
        -o) shift; owner="$1"; shift ;;
        -t) shift; github_token="$1"; shift ;;
        -r) shift; repository="$1"; shift ;;
        -p) shift; github_packages_token="$1"; shift ;;
    esac
done

if [ -z "$namespace" -o -z "$owner" -o -z "$github_token" ]; then
    echo "usage: deploy-actions-runner -n namespace -o owner -t token [-r repo] [ -p packages token ]"
    exit 0
fi

cat << EOF > yaml/github-settings.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
spec:
  template:
    spec:
      containers:
        - name: runner
          env:
            - name: GITHUB_OWNER
              value: $owner
            - name: GITHUB_REPOSITORY
              value: $repository
EOF

if [ ! -z github_packages_token ]; then
    kubectl create secret docker-registry github-packages \
        --dry-run \
        --docker-server=docker.pkg.github.com \
        --docker-username=$owner \
        --docker-password=$github_packages_token \
        -o yaml > yaml/github-packages-secret.yaml
fi

if [ ! -z $repository ]; then
    owner=$(echo $repository | tr / -)
fi

sed "s,@namespace@,$namespace,g
     s,@owner@,$owner,g
     s,@github_token@,$github_token,g
     " yaml/kustomization.in > yaml/kustomization.yaml

kubectl kustomize yaml
